---
title: "Populism Paper"
author: "Scott LaCombe"
date: "December 15, 2016"
output:
  html_document: default
  pdf_document: default
bibliography: sources.bib
---


```{r setup, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
knitr::opts_chunk$set(echo = TRUE)

```


```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
   
if (!require(ghit)) install.packages("ghit")
   library(ghit)
   ghit::install_github("fsolt/icpsrdata")
   library(icpsrdata)
  data <- icpsr_download(file_id= 36390, email = getOption("icpsr_email"), password = getOption("icpsr_password"), reset = FALSE, download_dir = "icpsr_data")

  
unzip(zipfile = "36390-Zipped_package.zip")
  
  ANES <- import("anes_pilot_2016.sav")

#import dataset from file. Transfer from zip file to working directory
  
```


```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
# recoding commands

if(!require('car')) install.packages("car")
  library(car)

ANES$Male <- recode(ANES$gender, "2=0;1=1")
ANES$Male

# feeling thermometers
ANES$fttrump <- recode(ANES$fttrump, "998=NA")
ANES$ftsanders <- recode(ANES$ftsanders, "998=NA")
ANES$fthrc <- recode(ANES$fthrc, "998=NA")
ANES$ftrubio <- recode(ANES$ftrubio, "998=NA")

# age 
ANES$age<- 2016-ANES$birthyr

# White dummy 
ANES$white <- recode(ANES$race, "2:8=0; 1=1")

# Employment dummy
ANES$employed <-recode(ANES$employ, " 3:9=0; 1=1; 2=1")


#5 point ideology- Most conservative=5
ANES$Conservative <- recode(ANES$ideo5, "6=NA")


#7 point partisanship- Very Republican=7 
ANES$Republican <- recode(ANES$pid7, "8=NA")

#Religion- Protestant dummy
ANES$Protestant <- recode(ANES$religpew, "2:98=0; 1=1")

#Opportunity to get ahead- 5= great deal 
ANES$getahead <- recode(ANES$getahead, "8=NA")


#legal immigration impact 
ANES$immlegal <-recode(ANES$immig_legal, "1=7; 2=6; 3=5;4=4;5=3;6=2;7=1")


# Support for Campaign Finance Reform 
ANES$campfinance <-recode(ANES$campfin, "1=7; 2=6; 3=5;4=4;5=3;6=2;7=1")


# Free Trade
ANES$freetrade <-recode(ANES$freetrade, "1=7; 2=6; 3=5;4=4;5=3;6=2;7=1")


#Should Politicians Stick to Principles or Compromise 
ANES$principles <-recode(ANES$compromise, "1=0;2=1")


# American Identity 
ANES$americanid <-recode(ANES$amer_ident, "1=5; 2=4; 3=3; 4=2; 5=1")


# Perception of Income Gap
ANES$inequality <-recode(ANES$incgap20, "5=1; 4=2; 3=3;4=2; 5=1; 8=NA")


# Require Vaccines 
ANES$vaccine <-recode(ANES$vaccine, "1=7; 2=6; 3=5; 4=4; 5=3;6=2;7=1")


#Ability to Improve financial well-being
ANES$finwell <-recode(ANES$finwell, "1=7; 2=6; 3=5; 4=4; 5=3;6=2;7=1; 8=NA")


# Move up the income ladder- easier/harder
ANES$ladder <-recode(ANES$ladder, "1=7; 2=6; 3=5; 4=4; 5=3;6=2;7=1; 8=NA")


#political knowledge dummy- correct number of years for a senator
ANES$polknow<- recode(ANES$pk_sen, "1:5=0; 7:998=0; 6=1") 
 

#economic evaluations
ANES$econnow <- recode(ANES$econnow, "5=1; 4=2; 3=3; 2=4; 1=5")


#income 
ANES$income <- recode(ANES$faminc, "1=1; 2=2; 3=3; 4=4; 5=5; 6=6; 7=7; 8=8; 9=9; 10=10; 11=11; 12/31=12; 97/98=NA")




```


```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
#regression models for comparative understanding


compoptrump <- lm(fttrump~ freetrade+principles+ americanid+ age + Male + white + employed + Republican + Conservative + income+ educ, data=ANES, weights=weight)

compoprubio <- lm(ftrubio~ freetrade+principles+ americanid+ age + Male + white + employed + Republican + Conservative + income + educ, data=ANES, weights=weight)

compopsanders <-lm(ftsanders~ freetrade+principles+ americanid+ age + Male + white + employed + Republican + Conservative +income + educ, data=ANES, weights=weight)

compophrc <- lm(fthrc~ freetrade+principles+ americanid+ age + Male + white + employed + Republican + Conservative + income+ educ, data=ANES, weights=weight)
```


```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
#regression models for Huntington's Credd

huntpoptrump <- lm(fttrump~ campfinance+ percent16 + inequality + vaccine + finwell + age + Male + white + employed + Republican + Conservative + income, data=ANES, weights=weight)

huntpoprubio <- lm(ftrubio~ campfinance+ percent16 + inequality + vaccine + finwell + age + Male + white + employed + Republican + Conservative + income, data=ANES, weights=weight)

huntpopsanders<- lm(ftsanders~ campfinance+ percent16 + inequality + vaccine + finwell + age + Male + white + employed + Republican + Conservative + income, data=ANES, weights=weight)

huntpophrc <- lm(fthrc~ campfinance+ percent16 + inequality + vaccine + finwell + age + Male + white + employed + Republican + Conservative + income, data=ANES, weights=weight)
```


```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
hofpoptrump <- lm(fttrump~ econnow+ immlegal+ campfinance + age + Male + white + employed+ Republican + Conservative +income + educ, data=ANES, weights=weight)

hofpoprubio <- lm(ftrubio~ econnow+ immlegal+ campfinance+ age + Male + white + employed+ Republican + Conservative + income + educ, data=ANES, weights=weight)

hofpopsanders <- lm(ftsanders~ econnow+ immlegal+ campfinance+ age + Male + white + employed+ Republican + Conservative + income + educ, data=ANES, weights=weight)

hofpophrc <- lm(fthrc~ econnow+ immlegal+ campfinance+ age + Male + white + employed+ Republican + Conservative + income + educ, data=ANES, weights=weight)

```



```{r echo=FALSE, warning=FALSE, message=FALSE}

if(!require('stargazer')) install.packages("stargazer")
  library(stargazer)
if(!require('rio')) install.packages("rio")
  library(rio)

ComparativePopulist <- stargazer(compoptrump, compoprubio, compopsanders, compophrc, title="Comparative Populist Measures", single.row=TRUE,
ci=TRUE, ci.level=0.95, align=TRUE)


ComparativePopulism <- stargazer(compoptrump, compoprubio, compopsanders, compophrc, title="Comparative Populist Measures", single.row=TRUE,
ci=TRUE, ci.level=0.95, align=TRUE)

HuntingtonCreed <- stargazer(huntpoptrump, huntpoprubio, huntpopsanders, huntpophrc, title="Comparative Populist Measures", single.row=TRUE,
ci=TRUE, ci.level=0.95, align=TRUE)

HofstaderPopulism <- stargazer(hofpoptrump, hofpoprubio, hofpopsanders, hofpophrc, title="Comparative Populist Measures", single.row=TRUE,
ci=TRUE, ci.level=0.95, align=TRUE)


```


```{r echo=FALSE}

if(!require('dotwhisker')) install.packages("dotwhisker")
  library(dotwhisker)
if(!require('broom')) install.packages("broom")
  library(broom)
if(!require('dplyr')) install.packages("dplyr")
  library(dplyr)

rubiodt <- tidy(compoprubio)%>% filter(term !="(Intercept)") %>% mutate(model="Rubio") 
trumpdt <- tidy(compoptrump)%>% filter(term !="(Intercept)") %>% mutate(model="Trump") 
sandersdt <- tidy(compopsanders)%>% filter(term !="(Intercept)") %>% mutate(model="Sanders") 
hrcdt <- tidy(compophrc)%>% filter(term !="(Intercept)") %>% mutate(model="Clinton") 


four_models <- rbind(rubiodt, trumpdt, sandersdt, hrcdt)

dwplot(four_models) + relabel_y_axis(c("Free Trade", "No Compromise", "Americand Identity", "Age", "Male", "White", "Employed", "Republicanism", "Conservatism", "Income", "Education")) + xlab("Coefficient Estimate") + 
  geom_vline(xintercept=0)+ 
  ggtitle("Determinants of Candidate Approval") +
 xlab("Coefficient Estimate")
    

```


```{r}

rubiodt2 <- tidy(hofpoprubio)%>% filter(term !="(Intercept)") %>% mutate(model="Rubio") 
trumpdt2 <- tidy(hofpoptrump)%>% filter(term !="(Intercept)") %>% mutate(model="Trump") 
sandersdt2 <- tidy(hofpopsanders)%>% filter(term !="(Intercept)") %>% mutate(model="Sanders") 
hrcdt2 <- tidy(hofpophrc)%>% filter(term !="(Intercept)") %>% mutate(model="Clinton") 


four_models2 <- rbind(rubiodt2, trumpdt2, sandersdt2, hrcdt2)

dwplot(four_models2) + relabel_y_axis(c("Current Economy", "Legal Immigration", "Campaign Finance Ref", "Age", "Male", "White", "Employed", "Republicanism", "Conservatism", "Income", "Education")) + xlab("Coefficient Estimate") + 
  geom_vline(xintercept=0)+ 
  ggtitle("Determinants of Candidate Approval") +
 xlab("Coefficient Estimate")

   
```

```{r}

rubiodt3 <- tidy(huntpoprubio)%>% filter(term !="(Intercept)") %>% mutate(model="Rubio") 
trumpdt3 <- tidy(huntpoptrump)%>% filter(term !="(Intercept)") %>% mutate(model="Trump") 
sandersdt3 <- tidy(huntpopsanders)%>% filter(term !="(Intercept)") %>% mutate(model="Sanders") 
hrcdt3 <- tidy(huntpophrc)%>% filter(term !="(Intercept)") %>% mutate(model="Clinton") 


four_models3 <- rbind(rubiodt3, trumpdt3, sandersdt3, hrcdt3)

dwplot(four_models3) + relabel_y_axis(c("Campaign Finance Ref", "Chance of Voting", "Inequality Perception", "Vaccine Requirement", "Age", "Male", "White", "Employed", "Republicanism", "Conservatism", "Income", "Education")) + xlab("Coefficient Estimate") + 
  geom_vline(xintercept=0)+ 
  ggtitle("Determinants of Candidate Approval") +
 xlab("Coefficient Estimate")
```

#References

